
# Default Site settings
# --------------------------------
title: justus' homepage - v2.0
email: me@justus.science
description: > # this means to ignore newlines until "baseurl:"
  This page is about who I am and what I do. Plus it contains my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justus.science" # the base hostname & protocol for your site
twitter_username: justusadam_
github_username:  justusadam

# --------------------------------

exclude:
  - _purescript

# Custom additions
# --------------------------------
quick_view_length: 100
paginate: 5
snippet_base_url: "https://github.com/JustusAdam/justusadam.github.io/tree/master/_includes"

page_logo:
  default: /images/logo.png
  svg: /images/lambda-logo-filled-gradient.svg
  small: /images/logo.png

# --------------------------------

# Build settings
# --------------------------------
markdown: kramdown

sass:
  style: :compressed

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: blog
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      category: drafts
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "legal"
    values:
      layout: "default"

collections:
  projects:
    output: true
  legal:
    output: true
  quick_facts:

# --------------------------------
