# Site settings
title: Justus Adam's Homepage
email: justus@justusadam.com
description: > # this means to ignore newlines until "baseurl:"
  This page is about who I am and what I do. Soon it shall also again
  contain my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justusadam.com" # the base hostname & protocol for your site
twitter_username: justusadam_
github_username:  justusadam

# Build settings
markdown: kramdown

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      category: blog

collections:
  projects:
    output: false
