# Site settings
title: justus' homepage - v2.0
email: justus@justusadam.com
description: > # this means to ignore newlines until "baseurl:"
  This page is about who I am and what I do. Plus it contains my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justus.science" # the base hostname & protocol for your site
twitter_username: justusadam_
github_username:  justusadam
quick_view_length: 100
paginate: 5

# Build settings
markdown: kramdown

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: blog
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      category: drafts
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "legal"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "teachings"
    values:
      layout: "post"

collections:
  projects:
    output: true
  legal:
    output: true
  quick_facts:
  teachings:
    output: true
