title: justus' homepage - v2.0
email: me@justus.science
description: > # this means to ignore newlines until "baseurl:"
  Hello, my name is Justus Adam. I am a computer science student and this is my
  personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://justus.science" # the base hostname & protocol for your site
twitter_username: justusadam_
github_username:  justusadam
scholar_link: https://scholar.google.de/citations?user=Tabbno4AAAAJ

exclude:
  - _purescript
  - script
  - vendor

# Custom additions
# --------------------------------
quick_view_length: 100
paginate: 5
paginate_path: "blog/page:num/"
snippet_base_url: "https://github.com/JustusAdam/justusadam.github.io/tree/master/_includes"

page_logo:
  default: /images/logo.png
  svg: /images/lambda-logo-filled-gradient.svg
  small: /images/logo.png

# --------------------------------

# Build settings
# --------------------------------
markdown: kramdown

sass:
  style: :compressed

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript

feed:
  path: atom.xml

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: blog
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
      category: drafts
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "legal"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "england-blog"
    values:
      layout: "england-post"

collections:
  projects:
    output: true
  legal:
    output: true
  quick_facts:
  england-blog:
    output: true

# --------------------------------
