(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by psc-bundle 0.7.2.0
var PS = { };
(function(exports) {
  /* global exports */
  "use strict";

  // module Prelude

  //- Functor --------------------------------------------------------------------

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Prelude"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var Category = function (__superclass_Prelude$dotSemigroupoid_0, id) {
      this["__superclass_Prelude.Semigroupoid_0"] = __superclass_Prelude$dotSemigroupoid_0;
      this.id = id;
  };
  var Functor = function (map) {
      this.map = map;
  };
  var Apply = function (__superclass_Prelude$dotFunctor_0, apply) {
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.apply = apply;
  };
  var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.pure = pure;
  };
  var Bind = function (__superclass_Prelude$dotApply_0, bind) {
      this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
      this.bind = bind;
  };
  var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
      this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
      this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
  };
  var Show = function (show) {
      this.show = show;
  };                                                                           
  var unit = {};
  var show = function (dict) {
      return dict.show;
  };                                                                     
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });                 
  var pure = function (dict) {
      return dict.pure;
  };
  var $$return = function (__dict_Applicative_2) {
      return pure(__dict_Applicative_2);
  };
  var map = function (dict) {
      return dict.map;
  };
  var $less$dollar$greater = function (__dict_Functor_5) {
      return map(__dict_Functor_5);
  };
  var id = function (dict) {
      return dict.id;
  };
  var functorArray = new Functor($foreign.arrayMap);
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };
  var $$const = function (a) {
      return function (_75) {
          return a;
      };
  };
  var $$void = function (__dict_Functor_12) {
      return function (fa) {
          return $less$dollar$greater(__dict_Functor_12)($$const(unit))(fa);
      };
  };
  var compose = function (dict) {
      return dict.compose;
  };                                                   
  var $less$less$less = function (__dict_Semigroupoid_14) {
      return compose(__dict_Semigroupoid_14);
  };
  var $greater$greater$greater = function (__dict_Semigroupoid_15) {
      return flip(compose(__dict_Semigroupoid_15));
  };
  var categoryFn = new Category(function () {
      return semigroupoidFn;
  }, function (x) {
      return x;
  });
  var bind = function (dict) {
      return dict.bind;
  };
  var $greater$greater$eq = function (__dict_Bind_24) {
      return bind(__dict_Bind_24);
  }; 
  var apply = function (dict) {
      return dict.apply;
  };
  var $less$times$greater = function (__dict_Apply_25) {
      return apply(__dict_Apply_25);
  };
  var liftA1 = function (__dict_Applicative_26) {
      return function (f) {
          return function (a) {
              return $less$times$greater(__dict_Applicative_26["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_26)(f))(a);
          };
      };
  }; 
  var append = function (dict) {
      return dict.append;
  };
  var $less$greater = function (__dict_Semigroup_28) {
      return append(__dict_Semigroup_28);
  };
  var ap = function (__dict_Monad_30) {
      return function (f) {
          return function (a) {
              return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(f)(function (_16) {
                  return bind(__dict_Monad_30["__superclass_Prelude.Bind_1"]())(a)(function (_15) {
                      return $$return(__dict_Monad_30["__superclass_Prelude.Applicative_0"]())(_16(_15));
                  });
              });
          };
      };
  };
  exports["Show"] = Show;
  exports["Monad"] = Monad;
  exports["Bind"] = Bind;
  exports["Applicative"] = Applicative;
  exports["Apply"] = Apply;
  exports["Functor"] = Functor;
  exports["Category"] = Category;
  exports["Semigroupoid"] = Semigroupoid;
  exports["show"] = show;
  exports["<>"] = $less$greater;
  exports["append"] = append;
  exports["ap"] = ap;
  exports["return"] = $$return;
  exports[">>="] = $greater$greater$eq;
  exports["bind"] = bind;
  exports["liftA1"] = liftA1;
  exports["pure"] = pure;
  exports["<*>"] = $less$times$greater;
  exports["apply"] = apply;
  exports["void"] = $$void;
  exports["<$>"] = $less$dollar$greater;
  exports["map"] = map;
  exports["id"] = id;
  exports[">>>"] = $greater$greater$greater;
  exports["<<<"] = $less$less$less;
  exports["compose"] = compose;
  exports["const"] = $$const;
  exports["flip"] = flip;
  exports["unit"] = unit;
  exports["semigroupoidFn"] = semigroupoidFn;
  exports["categoryFn"] = categoryFn;
  exports["functorArray"] = functorArray;;
 
})(PS["Prelude"] = PS["Prelude"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var $times$greater = function (__dict_Apply_1) {
      return function (a) {
          return function (b) {
              return Prelude["<*>"](__dict_Apply_1)(Prelude["<$>"](__dict_Apply_1["__superclass_Prelude.Functor_0"]())(Prelude["const"](Prelude.id(Prelude.categoryFn)))(a))(b);
          };
      };
  };
  exports["*>"] = $times$greater;;
 
})(PS["Control.Apply"] = PS["Control.Apply"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Control.Monad.Eff

  exports.returnE = function (a) {
    return function () {
      return a;
    };
  };

  exports.bindE = function (a) {
    return function (f) {
      return function () {
        return f(a())();
      };
    };
  };
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Control.Monad.Eff"];
  var Prelude = PS["Prelude"];     
  var monadEff = new Prelude.Monad(function () {
      return applicativeEff;
  }, function () {
      return bindEff;
  });
  var bindEff = new Prelude.Bind(function () {
      return applyEff;
  }, $foreign.bindE);
  var applyEff = new Prelude.Apply(function () {
      return functorEff;
  }, Prelude.ap(monadEff));
  var applicativeEff = new Prelude.Applicative(function () {
      return applyEff;
  }, $foreign.returnE);
  var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
  exports["functorEff"] = functorEff;
  exports["applyEff"] = applyEff;
  exports["applicativeEff"] = applicativeEff;
  exports["bindEff"] = bindEff;
  exports["monadEff"] = monadEff;;
 
})(PS["Control.Monad.Eff"] = PS["Control.Monad.Eff"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Element

  exports.unsafeGetElementById = function (targId) {
    return function (src) {
      return function () {
        return src.getElementById(targId);
      };
    };
  };

  exports.unsafeGetElementsByClassName = function (targId) {
    return function (src) {
      return function () {
        return Array.prototype.slice.call(src.getElementsByClassName(targId));
      };
    };
  };

  exports.unsafeGetElementsByName = function (targId) {
    return function (src) {
      return function () {
        return Array.prototype.slice.call(src.getElementsByName(targId));
      };
    };
  };

  exports.unsafeQuerySelector = function (selector) {
    return function (src) {
      return function () {
        return src.querySelector(selector);
      };
    };
  };

  exports.unsafeQuerySelectorAll = function (selector) {
    return function (src) {
      return function () {
        return src.querySelectorAll(selector);
      };
    };
  };

  exports.unsafeGetAttribute = function (name) {
    return function (src) {
      return function () {
        return src.getAttribute(name);
      };
    };
  };

  exports.unsafeSetAttribute = function (name) {
    return function (value) {
      return function (src) {
        return function () {
          src.setAttribute(name, value);
          return {};
        };
      };
    };
  };

  exports.unsafeHasAttribute = function (name) {
    return function (src) {
      return function () {
        return src.hasAttribute(name);
      };
    };
  };

  exports.unsafeRemoveAttribute = function (name) {
    return function (src) {
      return function () {
        src.removeAttribute(name);
        return {};
      };
    };
  };

  exports.unsafeGetStyleAttr = function (name) {
    return function (src) {
      return function () {
        return src.style[name];
      };
    };
  };

  exports.unsafeSetStyleAttr = function (name) {
    return function (value) {
      return function (src) {
        return function () {
          src.style[name] = value;
          return {};
        };
      };
    };
  };

  exports.unsafeChildren = function (src) {
    return function () {
      return Array.prototype.slice.call(src.children);
    };
  };

  exports.unsafeAppendChild = function (src) {
    return function (child) {
      return function () {
        return src.appendChild(child);
      };
    };
  };

  exports.unsafeInnerHTML = function (src) {
    return function () {
      return src.innerHTML;
    };
  };

  exports.unsafeSetInnerHTML = function (value) {
    return function (src) {
      return function () {
        src.innerHTML = value;
        return {};
      };
    };
  };

  exports.unsafeTextContent = function (src) {
    return function () {
      return src.textContent;
    };
  };

  exports.unsafeSetTextContent = function (value) {
    return function (src) {
      return function () {
        src.textContent = value;
        return {};
      };
    };
  };

  exports.unsafeValue = function (src) {
    return function () {
      return src.value;
    };
  };

  exports.unsafeSetValue = function (value) {
    return function (src) {
      return function () {
        src.value = value;
        return {};
      };
    };
  };

  exports.unsafeContentWindow = function (obj) {
    return function () {
      return obj.contentWindow;
    };
  };

  exports.unsafeClassAdd = function (value) {
    return function (src) {
      return function () {
        src.classList.add(value);
        return {};
      };
    };
  };

  exports.unsafeClassRemove = function (value) {
    return function (src) {
      return function () {
        src.classList.remove(value);
        return {};
      };
    };
  };

  exports.unsafeClassToggle = function (value) {
    return function (src) {
      return function () {
        src.classList.toggle(value);
        return {};
      };
    };
  };

  exports.unsafeClassContains = function (value) {
    return function (src) {
      return function () {
        return src.classList.contains(value);
      };
    };
  };

  exports.unsafeOffsetParent = function (src) {
    return function () {
      return src.offsetParent;
    };
  };

  exports.unsafeOffsetHeight = function (src) {
    return function () {
      return src.offsetHeight;
    };
  };

  exports.unsafeOffsetWidth = function (src) {
    return function () {
      return src.offsetWidth;
    };
  };

  exports.unsafeOffsetTop = function (src) {
    return function () {
      return src.offsetTop;
    };
  };

  exports.unsafeOffsetLeft = function (src) {
    return function () {
      return src.offsetLeft;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Element"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  exports["unsafeOffsetLeft"] = $foreign.unsafeOffsetLeft;
  exports["unsafeOffsetTop"] = $foreign.unsafeOffsetTop;
  exports["unsafeOffsetWidth"] = $foreign.unsafeOffsetWidth;
  exports["unsafeOffsetHeight"] = $foreign.unsafeOffsetHeight;
  exports["unsafeOffsetParent"] = $foreign.unsafeOffsetParent;
  exports["unsafeClassContains"] = $foreign.unsafeClassContains;
  exports["unsafeClassToggle"] = $foreign.unsafeClassToggle;
  exports["unsafeClassRemove"] = $foreign.unsafeClassRemove;
  exports["unsafeClassAdd"] = $foreign.unsafeClassAdd;
  exports["unsafeContentWindow"] = $foreign.unsafeContentWindow;
  exports["unsafeSetValue"] = $foreign.unsafeSetValue;
  exports["unsafeValue"] = $foreign.unsafeValue;
  exports["unsafeSetTextContent"] = $foreign.unsafeSetTextContent;
  exports["unsafeTextContent"] = $foreign.unsafeTextContent;
  exports["unsafeSetInnerHTML"] = $foreign.unsafeSetInnerHTML;
  exports["unsafeInnerHTML"] = $foreign.unsafeInnerHTML;
  exports["unsafeAppendChild"] = $foreign.unsafeAppendChild;
  exports["unsafeChildren"] = $foreign.unsafeChildren;
  exports["unsafeSetStyleAttr"] = $foreign.unsafeSetStyleAttr;
  exports["unsafeGetStyleAttr"] = $foreign.unsafeGetStyleAttr;
  exports["unsafeRemoveAttribute"] = $foreign.unsafeRemoveAttribute;
  exports["unsafeHasAttribute"] = $foreign.unsafeHasAttribute;
  exports["unsafeSetAttribute"] = $foreign.unsafeSetAttribute;
  exports["unsafeGetAttribute"] = $foreign.unsafeGetAttribute;
  exports["unsafeQuerySelectorAll"] = $foreign.unsafeQuerySelectorAll;
  exports["unsafeQuerySelector"] = $foreign.unsafeQuerySelector;
  exports["unsafeGetElementsByName"] = $foreign.unsafeGetElementsByName;
  exports["unsafeGetElementsByClassName"] = $foreign.unsafeGetElementsByClassName;
  exports["unsafeGetElementById"] = $foreign.unsafeGetElementById;;
 
})(PS["Data.DOM.Simple.Unsafe.Element"] = PS["Data.DOM.Simple.Unsafe.Element"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Utils

  exports.ensure3 = function (nothing) {
    return function (just) {
      return function (v) {
        if (v === undefined || v === null) {
          return nothing;
        } else {
          return just(v);
        }
      };
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Utils"] = PS["Data.DOM.Simple.Unsafe.Utils"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["mempty"] = mempty;;
 
})(PS["Data.Monoid"] = PS["Data.Monoid"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_Functor_Invariant = PS["Data.Functor.Invariant"];
  var Control_Alt = PS["Control.Alt"];
  var Control_Alternative = PS["Control.Alternative"];
  var Control_Extend = PS["Control.Extend"];
  var Control_MonadPlus = PS["Control.MonadPlus"];
  var Control_Plus = PS["Control.Plus"];
  var Data_Monoid = PS["Data.Monoid"];     
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;;
 
})(PS["Data.Maybe"] = PS["Data.Maybe"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_Maybe = PS["Data.Maybe"];     
  var ensure = $foreign.ensure3(Data_Maybe.Nothing.value)(Data_Maybe.Just.create);
  exports["ensure"] = ensure;;
 
})(PS["Data.DOM.Simple.Unsafe.Utils"] = PS["Data.DOM.Simple.Unsafe.Utils"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Foldable

  exports.foldrArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = len - 1; i >= 0; i--) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  };

  exports.foldlArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = 0; i < len; i++) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  };
 
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.Foldable"];
  var Prelude = PS["Prelude"];
  var Data_Monoid = PS["Data.Monoid"];
  var Control_Apply = PS["Control.Apply"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];     
  var Foldable = function (foldMap, foldl, foldr) {
      this.foldMap = foldMap;
      this.foldl = foldl;
      this.foldr = foldr;
  };
  var foldr = function (dict) {
      return dict.foldr;
  };
  var traverse_ = function (__dict_Applicative_0) {
      return function (__dict_Foldable_1) {
          return function (f) {
              return foldr(__dict_Foldable_1)(Prelude["<<<"](Prelude.semigroupoidFn)(Control_Apply["*>"](__dict_Applicative_0["__superclass_Prelude.Apply_0"]()))(f))(Prelude.pure(__dict_Applicative_0)(Prelude.unit));
          };
      };
  };
  var for_ = function (__dict_Applicative_2) {
      return function (__dict_Foldable_3) {
          return Prelude.flip(traverse_(__dict_Applicative_2)(__dict_Foldable_3));
      };
  };
  var foldl = function (dict) {
      return dict.foldl;
  }; 
  var foldableArray = new Foldable(function (__dict_Monoid_19) {
      return function (f) {
          return function (xs) {
              return foldr(foldableArray)(function (x) {
                  return function (acc) {
                      return Prelude["<>"](__dict_Monoid_19["__superclass_Prelude.Semigroup_0"]())(f(x))(acc);
                  };
              })(Data_Monoid.mempty(__dict_Monoid_19))(xs);
          };
      };
  }, $foreign.foldlArray, $foreign.foldrArray);
  var foldMap = function (dict) {
      return dict.foldMap;
  };
  exports["Foldable"] = Foldable;
  exports["for_"] = for_;
  exports["traverse_"] = traverse_;
  exports["foldMap"] = foldMap;
  exports["foldl"] = foldl;
  exports["foldr"] = foldr;
  exports["foldableArray"] = foldableArray;;
 
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Tuple = PS["Data.Tuple"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var DOM = PS["DOM"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Array = PS["Data.Array"];     
  var Element = function (appendChild, children, classAdd, classContains, classRemove, classToggle, contentWindow, getAttribute, getElementById, getElementsByClassName, getElementsByName, getStyleAttr, hasAttribute, innerHTML, offsetHeight, offsetLeft, offsetParent, offsetTop, offsetWidth, querySelector, querySelectorAll, removeAttribute, setAttribute, setInnerHTML, setStyleAttr, setTextContent, setValue, textContent, value) {
      this.appendChild = appendChild;
      this.children = children;
      this.classAdd = classAdd;
      this.classContains = classContains;
      this.classRemove = classRemove;
      this.classToggle = classToggle;
      this.contentWindow = contentWindow;
      this.getAttribute = getAttribute;
      this.getElementById = getElementById;
      this.getElementsByClassName = getElementsByClassName;
      this.getElementsByName = getElementsByName;
      this.getStyleAttr = getStyleAttr;
      this.hasAttribute = hasAttribute;
      this.innerHTML = innerHTML;
      this.offsetHeight = offsetHeight;
      this.offsetLeft = offsetLeft;
      this.offsetParent = offsetParent;
      this.offsetTop = offsetTop;
      this.offsetWidth = offsetWidth;
      this.querySelector = querySelector;
      this.querySelectorAll = querySelectorAll;
      this.removeAttribute = removeAttribute;
      this.setAttribute = setAttribute;
      this.setInnerHTML = setInnerHTML;
      this.setStyleAttr = setStyleAttr;
      this.setTextContent = setTextContent;
      this.setValue = setValue;
      this.textContent = textContent;
      this.value = value;
  };
  var value = function (dict) {
      return dict.value;
  };
  var textContent = function (dict) {
      return dict.textContent;
  };                                                                            
  var setValue = function (dict) {
      return dict.setValue;
  };
  var setTextContent = function (dict) {
      return dict.setTextContent;
  };
  var setStyleAttr = function (dict) {
      return dict.setStyleAttr;
  };
  var setInnerHTML = function (dict) {
      return dict.setInnerHTML;
  };
  var setAttribute = function (dict) {
      return dict.setAttribute;
  };
  var removeAttribute = function (dict) {
      return dict.removeAttribute;
  };
  var querySelectorAll = function (dict) {
      return dict.querySelectorAll;
  };
  var querySelector = function (dict) {
      return dict.querySelector;
  };
  var offsetWidth = function (dict) {
      return dict.offsetWidth;
  };
  var offsetTop = function (dict) {
      return dict.offsetTop;
  };
  var offsetParent = function (dict) {
      return dict.offsetParent;
  };
  var offsetLeft = function (dict) {
      return dict.offsetLeft;
  };
  var offsetHeight = function (dict) {
      return dict.offsetHeight;
  };
  var innerHTML = function (dict) {
      return dict.innerHTML;
  };
  var htmlElement = new Element(Data_DOM_Simple_Unsafe_Element.unsafeAppendChild, Data_DOM_Simple_Unsafe_Element.unsafeChildren, Data_DOM_Simple_Unsafe_Element.unsafeClassAdd, Data_DOM_Simple_Unsafe_Element.unsafeClassContains, Data_DOM_Simple_Unsafe_Element.unsafeClassRemove, Data_DOM_Simple_Unsafe_Element.unsafeClassToggle, Data_DOM_Simple_Unsafe_Element.unsafeContentWindow, Data_DOM_Simple_Unsafe_Element.unsafeGetAttribute, function (id) {
      return function (el) {
          return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeGetElementById(id)(el))(Prelude[">>>"](Prelude.semigroupoidFn)(Data_DOM_Simple_Unsafe_Utils.ensure)(Prelude["return"](Control_Monad_Eff.applicativeEff)));
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByClassName, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByName, Data_DOM_Simple_Unsafe_Element.unsafeGetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeHasAttribute, Data_DOM_Simple_Unsafe_Element.unsafeInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeOffsetHeight, Data_DOM_Simple_Unsafe_Element.unsafeOffsetLeft, function (el) {
      return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeOffsetParent(el))(Prelude[">>>"](Prelude.semigroupoidFn)(Data_DOM_Simple_Unsafe_Utils.ensure)(Prelude["return"](Control_Monad_Eff.applicativeEff)));
  }, Data_DOM_Simple_Unsafe_Element.unsafeOffsetTop, Data_DOM_Simple_Unsafe_Element.unsafeOffsetWidth, function (sel) {
      return function (el) {
          return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(sel)(el))(Prelude[">>>"](Prelude.semigroupoidFn)(Data_DOM_Simple_Unsafe_Utils.ensure)(Prelude["return"](Control_Monad_Eff.applicativeEff)));
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeQuerySelectorAll, Data_DOM_Simple_Unsafe_Element.unsafeRemoveAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeSetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent, Data_DOM_Simple_Unsafe_Element.unsafeSetValue, Data_DOM_Simple_Unsafe_Element.unsafeTextContent, Data_DOM_Simple_Unsafe_Element.unsafeValue);
  var hasAttribute = function (dict) {
      return dict.hasAttribute;
  };
  var getStyleAttr = function (dict) {
      return dict.getStyleAttr;
  };
  var getElementsByName = function (dict) {
      return dict.getElementsByName;
  };
  var getElementsByClassName = function (dict) {
      return dict.getElementsByClassName;
  };
  var getElementById = function (dict) {
      return dict.getElementById;
  };
  var getAttribute = function (dict) {
      return dict.getAttribute;
  };                                                     
  var contentWindow = function (dict) {
      return dict.contentWindow;
  };                                                     
  var classToggle = function (dict) {
      return dict.classToggle;
  };
  var classRemove = function (dict) {
      return dict.classRemove;
  };
  var classContains = function (dict) {
      return dict.classContains;
  };
  var classAdd = function (dict) {
      return dict.classAdd;
  };
  var children = function (dict) {
      return dict.children;
  };                                                   
  var appendChild = function (dict) {
      return dict.appendChild;
  };
  exports["Element"] = Element;
  exports["offsetLeft"] = offsetLeft;
  exports["offsetTop"] = offsetTop;
  exports["offsetWidth"] = offsetWidth;
  exports["offsetHeight"] = offsetHeight;
  exports["offsetParent"] = offsetParent;
  exports["classContains"] = classContains;
  exports["classToggle"] = classToggle;
  exports["classAdd"] = classAdd;
  exports["classRemove"] = classRemove;
  exports["contentWindow"] = contentWindow;
  exports["setValue"] = setValue;
  exports["value"] = value;
  exports["setTextContent"] = setTextContent;
  exports["textContent"] = textContent;
  exports["setInnerHTML"] = setInnerHTML;
  exports["innerHTML"] = innerHTML;
  exports["appendChild"] = appendChild;
  exports["children"] = children;
  exports["setStyleAttr"] = setStyleAttr;
  exports["getStyleAttr"] = getStyleAttr;
  exports["removeAttribute"] = removeAttribute;
  exports["hasAttribute"] = hasAttribute;
  exports["setAttribute"] = setAttribute;
  exports["getAttribute"] = getAttribute;
  exports["querySelectorAll"] = querySelectorAll;
  exports["querySelector"] = querySelector;
  exports["getElementsByName"] = getElementsByName;
  exports["getElementsByClassName"] = getElementsByClassName;
  exports["getElementById"] = getElementById;
  exports["htmlElement"] = htmlElement;;
 
})(PS["Data.DOM.Simple.Element"] = PS["Data.DOM.Simple.Element"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_DOM_Simple_Unsafe_Element = PS["Data.DOM.Simple.Unsafe.Element"];
  var Data_DOM_Simple_Unsafe_Utils = PS["Data.DOM.Simple.Unsafe.Utils"];
  var Data_DOM_Simple_Unsafe_Document = PS["Data.DOM.Simple.Unsafe.Document"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Element = PS["Data.DOM.Simple.Element"];
  var htmlDocumentElement = new Data_DOM_Simple_Element.Element(Data_DOM_Simple_Unsafe_Element.unsafeAppendChild, Data_DOM_Simple_Unsafe_Element.unsafeChildren, Data_DOM_Simple_Unsafe_Element.unsafeClassAdd, Data_DOM_Simple_Unsafe_Element.unsafeClassContains, Data_DOM_Simple_Unsafe_Element.unsafeClassRemove, Data_DOM_Simple_Unsafe_Element.unsafeClassToggle, Data_DOM_Simple_Unsafe_Element.unsafeContentWindow, Data_DOM_Simple_Unsafe_Element.unsafeGetAttribute, function (id) {
      return function (el) {
          return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeGetElementById(id)(el))(Prelude["<<<"](Prelude.semigroupoidFn)(Prelude["return"](Control_Monad_Eff.applicativeEff))(Data_DOM_Simple_Unsafe_Utils.ensure));
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByClassName, Data_DOM_Simple_Unsafe_Element.unsafeGetElementsByName, Data_DOM_Simple_Unsafe_Element.unsafeGetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeHasAttribute, Data_DOM_Simple_Unsafe_Element.unsafeInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeOffsetHeight, Data_DOM_Simple_Unsafe_Element.unsafeOffsetLeft, function (el) {
      return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeOffsetParent(el))(Prelude[">>>"](Prelude.semigroupoidFn)(Data_DOM_Simple_Unsafe_Utils.ensure)(Prelude["return"](Control_Monad_Eff.applicativeEff)));
  }, Data_DOM_Simple_Unsafe_Element.unsafeOffsetTop, Data_DOM_Simple_Unsafe_Element.unsafeOffsetWidth, function (sel) {
      return function (el) {
          return Prelude[">>="](Control_Monad_Eff.bindEff)(Data_DOM_Simple_Unsafe_Element.unsafeQuerySelector(sel)(el))(Prelude["<<<"](Prelude.semigroupoidFn)(Prelude["return"](Control_Monad_Eff.applicativeEff))(Data_DOM_Simple_Unsafe_Utils.ensure));
      };
  }, Data_DOM_Simple_Unsafe_Element.unsafeQuerySelectorAll, Data_DOM_Simple_Unsafe_Element.unsafeRemoveAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetAttribute, Data_DOM_Simple_Unsafe_Element.unsafeSetInnerHTML, Data_DOM_Simple_Unsafe_Element.unsafeSetStyleAttr, Data_DOM_Simple_Unsafe_Element.unsafeSetTextContent, Data_DOM_Simple_Unsafe_Element.unsafeSetValue, Data_DOM_Simple_Unsafe_Element.unsafeTextContent, Data_DOM_Simple_Unsafe_Element.unsafeValue);
  exports["htmlDocumentElement"] = htmlDocumentElement;;
 
})(PS["Data.DOM.Simple.Document"] = PS["Data.DOM.Simple.Document"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Events

  exports.unsafeAddEventListener = function (targ) {
    return function (cb) {
      return function (src) {
        return function () {
          src.addEventListener(targ, function (evt) {
            cb(evt)();
          });
        };
      };
    };
  };

  exports.unsafeRemoveEventListener = function (targ) {
    return function (cb) {
      return function (src) {
        return function () {
          src.removeEventListener(targ, function (evt) {
            cb(evt)();
          });
        };
      };
    };
  };

  exports.unsafeEventTarget = function (event) {
    return function () {
      return event.target;
    };
  };

  exports.unsafeStopPropagation = function (event) {
    return function () {
      event.stopPropagation();
    };
  };

  exports.unsafePreventDefault = function (event) {
    return function () {
      event.preventDefault();
    };
  };

  exports.unsafeEventNumberProp = function (prop) {
    return function (event) {
      return function () {
        return event[prop];
      };
    };
  };

  exports.unsafeEventStringProp = function (prop) {
    return function (event) {
      return function () {
        return event[prop];
      };
    };
  };

  // XXX really should be returning an HTMLAbstractView here...
  exports.unsafeEventView = function (event) {
    return function () {
      return event.view;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Events"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  exports["unsafeEventView"] = $foreign.unsafeEventView;
  exports["unsafeEventStringProp"] = $foreign.unsafeEventStringProp;
  exports["unsafeEventNumberProp"] = $foreign.unsafeEventNumberProp;
  exports["unsafePreventDefault"] = $foreign.unsafePreventDefault;
  exports["unsafeStopPropagation"] = $foreign.unsafeStopPropagation;
  exports["unsafeEventTarget"] = $foreign.unsafeEventTarget;
  exports["unsafeRemoveEventListener"] = $foreign.unsafeRemoveEventListener;
  exports["unsafeAddEventListener"] = $foreign.unsafeAddEventListener;;
 
})(PS["Data.DOM.Simple.Unsafe.Events"] = PS["Data.DOM.Simple.Unsafe.Events"] || {});
(function(exports) {
  /* global exports, window */
  "use strict";

  // module Data.DOM.Simple.Window

  exports.globalWindow = window;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.DOM.Simple.Unsafe.Window

  exports.unsafeDocument = function (win) {
    return function () {
      return win.document;
    };
  };

  exports.unsafeNavigator = function (win) {
    return function () {
      return win.navigator;
    };
  };

  exports.unsafeLocation = function (win) {
    return function () {
      return win.location;
    };
  };

  exports.unsafeSetTimeout = function (win) {
    return function (delay) {
      return function (func) {
        return function () {
          return win.setTimeout(func, delay);
        };
      };
    };
  };

  exports.unsafeSetInterval = function (win) {
    return function (delay) {
      return function (func) {
        return function () {
          return win.setInterval(func, delay);
        };
      };
    };
  };

  exports.unsafeClearTimeout = function (win) {
    return function (timeout) {
      return function () {
        win.clearTimeout(timeout);
      };
    };
  };

  exports.unsafeInnerWidth = function (win) {
    return function () {
      return win.innerWidth;
    };
  };

  exports.unsafeInnerHeight = function (win) {
    return function () {
      return win.innerHeight;
    };
  };
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  exports["unsafeInnerHeight"] = $foreign.unsafeInnerHeight;
  exports["unsafeInnerWidth"] = $foreign.unsafeInnerWidth;
  exports["unsafeClearTimeout"] = $foreign.unsafeClearTimeout;
  exports["unsafeSetInterval"] = $foreign.unsafeSetInterval;
  exports["unsafeSetTimeout"] = $foreign.unsafeSetTimeout;
  exports["unsafeLocation"] = $foreign.unsafeLocation;
  exports["unsafeNavigator"] = $foreign.unsafeNavigator;
  exports["unsafeDocument"] = $foreign.unsafeDocument;;
 
})(PS["Data.DOM.Simple.Unsafe.Window"] = PS["Data.DOM.Simple.Unsafe.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.DOM.Simple.Window"];
  var Data_DOM_Simple_Unsafe_Window = PS["Data.DOM.Simple.Unsafe.Window"];
  var Prelude = PS["Prelude"];
  var Data_String = PS["Data.String"];
  var Data_Array = PS["Data.Array"];
  var DOM = PS["DOM"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_Maybe = PS["Data.Maybe"];
  var Window = function (clearTimeout, document, innerHeight, innerWidth, location, navigator, setInterval, setTimeout) {
      this.clearTimeout = clearTimeout;
      this.document = document;
      this.innerHeight = innerHeight;
      this.innerWidth = innerWidth;
      this.location = location;
      this.navigator = navigator;
      this.setInterval = setInterval;
      this.setTimeout = setTimeout;
  };
  var setTimeout = function (dict) {
      return dict.setTimeout;
  };
  var setInterval = function (dict) {
      return dict.setInterval;
  };
  var navigator = function (dict) {
      return dict.navigator;
  };
  var location = function (dict) {
      return dict.location;
  };
  var innerWidth = function (dict) {
      return dict.innerWidth;
  };
  var innerHeight = function (dict) {
      return dict.innerHeight;
  };
  var htmlWindow = new Window(Data_DOM_Simple_Unsafe_Window.unsafeClearTimeout, Data_DOM_Simple_Unsafe_Window.unsafeDocument, Data_DOM_Simple_Unsafe_Window.unsafeInnerHeight, Data_DOM_Simple_Unsafe_Window.unsafeInnerWidth, Data_DOM_Simple_Unsafe_Window.unsafeLocation, Data_DOM_Simple_Unsafe_Window.unsafeNavigator, Data_DOM_Simple_Unsafe_Window.unsafeSetInterval, Data_DOM_Simple_Unsafe_Window.unsafeSetTimeout);
  var document = function (dict) {
      return dict.document;
  };
  var clearTimeout = function (dict) {
      return dict.clearTimeout;
  };
  exports["Window"] = Window;
  exports["innerHeight"] = innerHeight;
  exports["innerWidth"] = innerWidth;
  exports["clearTimeout"] = clearTimeout;
  exports["setInterval"] = setInterval;
  exports["setTimeout"] = setTimeout;
  exports["location"] = location;
  exports["navigator"] = navigator;
  exports["document"] = document;
  exports["htmlWindow"] = htmlWindow;
  exports["globalWindow"] = $foreign.globalWindow;;
 
})(PS["Data.DOM.Simple.Window"] = PS["Data.DOM.Simple.Window"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Data_DOM_Simple_Unsafe_Events = PS["Data.DOM.Simple.Unsafe.Events"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad = PS["Control.Monad"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var Data_DOM_Simple_Ajax = PS["Data.DOM.Simple.Ajax"];
  var DOM = PS["DOM"];     
  var LoadEvent = (function () {
      function LoadEvent() {

      };
      LoadEvent.value = new LoadEvent();
      return LoadEvent;
  })();
  var UnloadEvent = (function () {
      function UnloadEvent() {

      };
      UnloadEvent.value = new UnloadEvent();
      return UnloadEvent;
  })();
  var AbortEvent = (function () {
      function AbortEvent() {

      };
      AbortEvent.value = new AbortEvent();
      return AbortEvent;
  })();
  var ErrorEvent = (function () {
      function ErrorEvent() {

      };
      ErrorEvent.value = new ErrorEvent();
      return ErrorEvent;
  })();
  var SelectEvent = (function () {
      function SelectEvent() {

      };
      SelectEvent.value = new SelectEvent();
      return SelectEvent;
  })();
  var ResizeEvent = (function () {
      function ResizeEvent() {

      };
      ResizeEvent.value = new ResizeEvent();
      return ResizeEvent;
  })();
  var ScrollEvent = (function () {
      function ScrollEvent() {

      };
      ScrollEvent.value = new ScrollEvent();
      return ScrollEvent;
  })();
  var MouseMoveEvent = (function () {
      function MouseMoveEvent() {

      };
      MouseMoveEvent.value = new MouseMoveEvent();
      return MouseMoveEvent;
  })();
  var MouseOverEvent = (function () {
      function MouseOverEvent() {

      };
      MouseOverEvent.value = new MouseOverEvent();
      return MouseOverEvent;
  })();
  var MouseEnterEvent = (function () {
      function MouseEnterEvent() {

      };
      MouseEnterEvent.value = new MouseEnterEvent();
      return MouseEnterEvent;
  })();
  var MouseOutEvent = (function () {
      function MouseOutEvent() {

      };
      MouseOutEvent.value = new MouseOutEvent();
      return MouseOutEvent;
  })();
  var MouseLeaveEvent = (function () {
      function MouseLeaveEvent() {

      };
      MouseLeaveEvent.value = new MouseLeaveEvent();
      return MouseLeaveEvent;
  })();
  var MouseClickEvent = (function () {
      function MouseClickEvent() {

      };
      MouseClickEvent.value = new MouseClickEvent();
      return MouseClickEvent;
  })();
  var MouseDblClickEvent = (function () {
      function MouseDblClickEvent() {

      };
      MouseDblClickEvent.value = new MouseDblClickEvent();
      return MouseDblClickEvent;
  })();
  var MouseUpEvent = (function () {
      function MouseUpEvent() {

      };
      MouseUpEvent.value = new MouseUpEvent();
      return MouseUpEvent;
  })();
  var MouseDownEvent = (function () {
      function MouseDownEvent() {

      };
      MouseDownEvent.value = new MouseDownEvent();
      return MouseDownEvent;
  })();
  var Read = function (read) {
      this.read = read;
  };
  var Event = function (eventTarget, preventDefault, stopPropagation) {
      this.eventTarget = eventTarget;
      this.preventDefault = preventDefault;
      this.stopPropagation = stopPropagation;
  };
  var MouseEvent = function (__superclass_Data$dotDOM$dotSimple$dotEvents$dotEvent_0, mouseEventType, screenX, screenY) {
      this["__superclass_Data.DOM.Simple.Events.Event_0"] = __superclass_Data$dotDOM$dotSimple$dotEvents$dotEvent_0;
      this.mouseEventType = mouseEventType;
      this.screenX = screenX;
      this.screenY = screenY;
  };
  var MouseEventTarget = function (addMouseEventListener, removeMouseEventListener) {
      this.addMouseEventListener = addMouseEventListener;
      this.removeMouseEventListener = removeMouseEventListener;
  };
  var UIEvent = function (__superclass_Data$dotDOM$dotSimple$dotEvents$dotEvent_0, detail, view) {
      this["__superclass_Data.DOM.Simple.Events.Event_0"] = __superclass_Data$dotDOM$dotSimple$dotEvents$dotEvent_0;
      this.detail = detail;
      this.view = view;
  };
  var UIEventTarget = function (addUIEventListener, removeUIEventListener) {
      this.addUIEventListener = addUIEventListener;
      this.removeUIEventListener = removeUIEventListener;
  };
  var view = function (dict) {
      return dict.view;
  };
  var uiEventTypeShow = new Prelude.Show(function (_490) {
      if (_490 instanceof LoadEvent) {
          return "load";
      };
      if (_490 instanceof UnloadEvent) {
          return "unload";
      };
      if (_490 instanceof AbortEvent) {
          return "abort";
      };
      if (_490 instanceof ErrorEvent) {
          return "error";
      };
      if (_490 instanceof SelectEvent) {
          return "select";
      };
      if (_490 instanceof ResizeEvent) {
          return "resize";
      };
      if (_490 instanceof ScrollEvent) {
          return "scroll";
      };
      throw new Error("Failed pattern match at Data.DOM.Simple.Events line 176, column 1 - line 185, column 1: " + [ _490.constructor.name ]);
  });
  var uiEventTargetHTMLWindow = new UIEventTarget(function (__dict_UIEvent_0) {
      return function (typ) {
          return Data_DOM_Simple_Unsafe_Events.unsafeAddEventListener(Prelude.show(uiEventTypeShow)(typ));
      };
  }, function (__dict_UIEvent_1) {
      return function (typ) {
          return Data_DOM_Simple_Unsafe_Events.unsafeRemoveEventListener(Prelude.show(uiEventTypeShow)(typ));
      };
  });
  var stopPropagation = function (dict) {
      return dict.stopPropagation;
  };
  var screenY = function (dict) {
      return dict.screenY;
  };
  var screenX = function (dict) {
      return dict.screenX;
  };
  var removeUIEventListener = function (dict) {
      return dict.removeUIEventListener;
  };
  var removeMouseEventListener = function (dict) {
      return dict.removeMouseEventListener;
  };
  var read = function (dict) {
      return dict.read;
  };
  var preventDefault = function (dict) {
      return dict.preventDefault;
  };
  var mouseEventTypeShow = new Prelude.Show(function (_486) {
      if (_486 instanceof MouseMoveEvent) {
          return "mousemove";
      };
      if (_486 instanceof MouseOverEvent) {
          return "mouseover";
      };
      if (_486 instanceof MouseEnterEvent) {
          return "mouseenter";
      };
      if (_486 instanceof MouseOutEvent) {
          return "mouseout";
      };
      if (_486 instanceof MouseLeaveEvent) {
          return "mouseleave";
      };
      if (_486 instanceof MouseClickEvent) {
          return "click";
      };
      if (_486 instanceof MouseDblClickEvent) {
          return "dblclick";
      };
      if (_486 instanceof MouseUpEvent) {
          return "mouseup";
      };
      if (_486 instanceof MouseDownEvent) {
          return "mousedown";
      };
      throw new Error("Failed pattern match at Data.DOM.Simple.Events line 36, column 1 - line 47, column 1: " + [ _486.constructor.name ]);
  });
  var mouseEventTypeRead = new Read(function (_487) {
      if (_487 === "mousemove") {
          return MouseMoveEvent.value;
      };
      if (_487 === "mouseover") {
          return MouseOverEvent.value;
      };
      if (_487 === "mouseenter") {
          return MouseEnterEvent.value;
      };
      if (_487 === "mouseout") {
          return MouseOutEvent.value;
      };
      if (_487 === "mouseleave") {
          return MouseLeaveEvent.value;
      };
      if (_487 === "click") {
          return MouseClickEvent.value;
      };
      if (_487 === "dblclick") {
          return MouseDblClickEvent.value;
      };
      if (_487 === "mouseup") {
          return MouseUpEvent.value;
      };
      if (_487 === "mousedown") {
          return MouseDownEvent.value;
      };
      throw new Error("Failed pattern match at Data.DOM.Simple.Events line 47, column 1 - line 58, column 1: " + [ _487.constructor.name ]);
  });
  var mouseEventType = function (dict) {
      return dict.mouseEventType;
  }; 
  var mouseEventTargetHTMLElement = new MouseEventTarget(function (__dict_MouseEvent_4) {
      return function (typ) {
          return Data_DOM_Simple_Unsafe_Events.unsafeAddEventListener(Prelude.show(mouseEventTypeShow)(typ));
      };
  }, function (__dict_MouseEvent_5) {
      return function (typ) {
          return Data_DOM_Simple_Unsafe_Events.unsafeRemoveEventListener(Prelude.show(mouseEventTypeShow)(typ));
      };
  });
  var eventTarget = function (dict) {
      return dict.eventTarget;
  };
  var eventDOMEvent = new Event(Data_DOM_Simple_Unsafe_Events.unsafeEventTarget, Data_DOM_Simple_Unsafe_Events.unsafePreventDefault, Data_DOM_Simple_Unsafe_Events.unsafeStopPropagation);
  var mouseEventDOMEvent = new MouseEvent(function () {
      return eventDOMEvent;
  }, function (ev) {
      return Prelude["<$>"](Control_Monad_Eff.functorEff)(read(mouseEventTypeRead))(Data_DOM_Simple_Unsafe_Events.unsafeEventStringProp("type")(ev));
  }, Data_DOM_Simple_Unsafe_Events.unsafeEventNumberProp("screenX"), Data_DOM_Simple_Unsafe_Events.unsafeEventNumberProp("screenY"));
  var uiEventDOMEvent = new UIEvent(function () {
      return eventDOMEvent;
  }, Data_DOM_Simple_Unsafe_Events.unsafeEventNumberProp("detail"), Data_DOM_Simple_Unsafe_Events.unsafeEventView);
  var detail = function (dict) {
      return dict.detail;
  };
  var addUIEventListener = function (dict) {
      return dict.addUIEventListener;
  };
  var addMouseEventListener = function (dict) {
      return dict.addMouseEventListener;
  };
  exports["LoadEvent"] = LoadEvent;
  exports["UnloadEvent"] = UnloadEvent;
  exports["AbortEvent"] = AbortEvent;
  exports["ErrorEvent"] = ErrorEvent;
  exports["SelectEvent"] = SelectEvent;
  exports["ResizeEvent"] = ResizeEvent;
  exports["ScrollEvent"] = ScrollEvent;
  exports["MouseMoveEvent"] = MouseMoveEvent;
  exports["MouseOverEvent"] = MouseOverEvent;
  exports["MouseEnterEvent"] = MouseEnterEvent;
  exports["MouseOutEvent"] = MouseOutEvent;
  exports["MouseLeaveEvent"] = MouseLeaveEvent;
  exports["MouseClickEvent"] = MouseClickEvent;
  exports["MouseDblClickEvent"] = MouseDblClickEvent;
  exports["MouseUpEvent"] = MouseUpEvent;
  exports["MouseDownEvent"] = MouseDownEvent;
  exports["UIEventTarget"] = UIEventTarget;
  exports["UIEvent"] = UIEvent;
  exports["MouseEventTarget"] = MouseEventTarget;
  exports["MouseEvent"] = MouseEvent;
  exports["Event"] = Event;
  exports["Read"] = Read;
  exports["removeUIEventListener"] = removeUIEventListener;
  exports["addUIEventListener"] = addUIEventListener;
  exports["detail"] = detail;
  exports["view"] = view;
  exports["removeMouseEventListener"] = removeMouseEventListener;
  exports["addMouseEventListener"] = addMouseEventListener;
  exports["screenY"] = screenY;
  exports["screenX"] = screenX;
  exports["mouseEventType"] = mouseEventType;
  exports["preventDefault"] = preventDefault;
  exports["stopPropagation"] = stopPropagation;
  exports["eventTarget"] = eventTarget;
  exports["read"] = read;
  exports["eventDOMEvent"] = eventDOMEvent;
  exports["mouseEventTypeShow"] = mouseEventTypeShow;
  exports["mouseEventTypeRead"] = mouseEventTypeRead;
  exports["mouseEventDOMEvent"] = mouseEventDOMEvent;
  exports["mouseEventTargetHTMLElement"] = mouseEventTargetHTMLElement;
  exports["uiEventTypeShow"] = uiEventTypeShow;
  exports["uiEventDOMEvent"] = uiEventDOMEvent;
  exports["uiEventTargetHTMLWindow"] = uiEventTargetHTMLWindow;;
 
})(PS["Data.DOM.Simple.Events"] = PS["Data.DOM.Simple.Events"] || {});
(function(exports) {
  /* global exports */
  "use strict";

  // module Data.Traversable

  // jshint maxparams: 3

  exports.traverseArrayImpl = function () {
    function Cont (fn) {
      this.fn = fn;
    }

    var emptyList = {};

    var ConsCell = function (head, tail) {
      this.head = head;
      this.tail = tail;
    };

    function consList (x) {
      return function (xs) {
        return new ConsCell(x, xs);
      };
    }

    function listToArray (list) {
      var arr = [];
      while (list !== emptyList) {
        arr.push(list.head);
        list = list.tail;
      }
      return arr;
    }

    return function (apply) {
      return function (map) {
        return function (pure) {
          return function (f) {
            var buildFrom = function (x, ys) {
              return apply(map(consList)(f(x)))(ys);
            };

            var go = function (acc, currentLen, xs) {
              if (currentLen === 0) {
                return acc;
              } else {
                var last = xs[currentLen - 1];
                return new Cont(function () {
                  return go(buildFrom(last, acc), currentLen - 1, xs);
                });
              }
            };

            return function (array) {
              var result = go(pure(emptyList), array.length, array);
              while (result instanceof Cont) {
                result = result.fn();
              }

              return map(listToArray)(result);
            };
          };
        };
      };
    };
  }();
 
})(PS["Data.Traversable"] = PS["Data.Traversable"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var $foreign = PS["Data.Traversable"];
  var Prelude = PS["Prelude"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_Maybe = PS["Data.Maybe"];
  var Data_Maybe_First = PS["Data.Maybe.First"];
  var Data_Maybe_Last = PS["Data.Maybe.Last"];
  var Data_Monoid_Additive = PS["Data.Monoid.Additive"];
  var Data_Monoid_Dual = PS["Data.Monoid.Dual"];
  var Data_Monoid_Multiplicative = PS["Data.Monoid.Multiplicative"];
  var Data_Monoid_Disj = PS["Data.Monoid.Disj"];
  var Data_Monoid_Conj = PS["Data.Monoid.Conj"];
  var Traversable = function (__superclass_Data$dotFoldable$dotFoldable_1, __superclass_Prelude$dotFunctor_0, sequence, traverse) {
      this["__superclass_Data.Foldable.Foldable_1"] = __superclass_Data$dotFoldable$dotFoldable_1;
      this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
      this.sequence = sequence;
      this.traverse = traverse;
  };
  var traverse = function (dict) {
      return dict.traverse;
  }; 
  var traversableArray = new Traversable(function () {
      return Data_Foldable.foldableArray;
  }, function () {
      return Prelude.functorArray;
  }, function (__dict_Applicative_11) {
      return traverse(traversableArray)(__dict_Applicative_11)(Prelude.id(Prelude.categoryFn));
  }, function (__dict_Applicative_10) {
      return $foreign.traverseArrayImpl(Prelude.apply(__dict_Applicative_10["__superclass_Prelude.Apply_0"]()))(Prelude.map((__dict_Applicative_10["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]()))(Prelude.pure(__dict_Applicative_10));
  });
  var sequence = function (dict) {
      return dict.sequence;
  }; 
  var $$for = function (__dict_Applicative_22) {
      return function (__dict_Traversable_23) {
          return function (x) {
              return function (f) {
                  return traverse(__dict_Traversable_23)(__dict_Applicative_22)(f)(x);
              };
          };
      };
  };
  exports["Traversable"] = Traversable;
  exports["for"] = $$for;
  exports["sequence"] = sequence;
  exports["traverse"] = traverse;
  exports["traversableArray"] = traversableArray;;
 
})(PS["Data.Traversable"] = PS["Data.Traversable"] || {});
(function(exports) {
  // Generated by psc version 0.7.2.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Data_DOM_Simple_Element = PS["Data.DOM.Simple.Element"];
  var Data_Foldable = PS["Data.Foldable"];
  var Data_DOM_Simple_Window = PS["Data.DOM.Simple.Window"];
  var Data_Traversable = PS["Data.Traversable"];
  var Data_DOM_Simple_Events = PS["Data.DOM.Simple.Events"];
  var Control_Monad_State_Class = PS["Control.Monad.State.Class"];
  var Control_Monad_State_Trans = PS["Control.Monad.State.Trans"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Control_Monad_Eff_Class = PS["Control.Monad.Eff.Class"];
  var Control_Monad_Trans = PS["Control.Monad.Trans"];
  var Control_Apply = PS["Control.Apply"];
  var Data_DOM_Simple_Document = PS["Data.DOM.Simple.Document"];
  var Data_DOM_Simple_Types = PS["Data.DOM.Simple.Types"];
  var Control_Monad_Eff_Console = PS["Control.Monad.Eff.Console"];
  var Data_Maybe = PS["Data.Maybe"];     
  var $amp = function (a) {
      return function (b) {
          return b(a);
      };
  };
  var toggleForks = function (__dict_Element_0) {
      return function (__dict_Element_1) {
          return function (forks) {
              return function (button) {
                  return function __do() {
                      var _0 = Data_DOM_Simple_Element.hasAttribute(__dict_Element_1)("checked")(button)();
                      return (function () {
                          var alterButton = $amp("checked")((function () {
                              if (_0) {
                                  return Data_DOM_Simple_Element.removeAttribute(__dict_Element_1);
                              };
                              if (!_0) {
                                  return Prelude.flip(Data_DOM_Simple_Element.setAttribute(__dict_Element_1))("");
                              };
                              throw new Error("Failed pattern match at Fork line 37, column 7 - line 43, column 3: " + [ _0.constructor.name ]);
                          })());
                          var alterElements = $amp("hidden")((function () {
                              if (_0) {
                                  return Data_DOM_Simple_Element.classAdd(__dict_Element_0);
                              };
                              if (!_0) {
                                  return Data_DOM_Simple_Element.classRemove(__dict_Element_0);
                              };
                              throw new Error("Failed pattern match at Fork line 43, column 7 - line 49, column 3: " + [ _0.constructor.name ]);
                          })());
                          return function __do() {
                              alterButton(button)();
                              return Data_Foldable.for_(Control_Monad_Eff.applicativeEff)(Data_Foldable.foldableArray)(forks)(alterElements)();
                          };
                      })()();
                  };
              };
          };
      };
  };
  var toggleForksEvent = function (__dict_Element_2) {
      return function (__dict_Element_3) {
          return function (a) {
              return function (b) {
                  return function (_4) {
                      return toggleForks(__dict_Element_2)(__dict_Element_3)(a)(b);
                  };
              };
          };
      };
  };
  var main = (function () {
      var main$prime = function (_5) {
          return function __do() {
              var _3 = Data_DOM_Simple_Window.document(Data_DOM_Simple_Window.htmlWindow)(Data_DOM_Simple_Window.globalWindow)();
              var _2 = Data_DOM_Simple_Element.getElementById(Data_DOM_Simple_Document.htmlDocumentElement)("toggle-forks")(_3)();
              return (function () {
                  if (_2 instanceof Data_Maybe.Just) {
                      return function __do() {
                          var _1 = Data_DOM_Simple_Element.getElementsByClassName(Data_DOM_Simple_Document.htmlDocumentElement)("is-fork")(_3)();
                          Data_Traversable["for"](Control_Monad_Eff.applicativeEff)(Data_Traversable.traversableArray)(_1)(Data_DOM_Simple_Element.classAdd(Data_DOM_Simple_Element.htmlElement)("hidden"))();
                          return Prelude["void"](Control_Monad_Eff.functorEff)(Data_DOM_Simple_Events.addMouseEventListener(Data_DOM_Simple_Events.mouseEventTargetHTMLElement)(Data_DOM_Simple_Events.mouseEventDOMEvent)(Data_DOM_Simple_Events.MouseClickEvent.value)(toggleForksEvent(Data_DOM_Simple_Element.htmlElement)(Data_DOM_Simple_Element.htmlElement)(_1)(_2.value0))(_2.value0))();
                      };
                  };
                  if (_2 instanceof Data_Maybe.Nothing) {
                      return Prelude["return"](Control_Monad_Eff.applicativeEff)(Prelude.unit);
                  };
                  throw new Error("Failed pattern match at Fork line 58, column 5 - line 59, column 5: " + [ _2.constructor.name ]);
              })()();
          };
      };
      return Data_DOM_Simple_Events.addUIEventListener(Data_DOM_Simple_Events.uiEventTargetHTMLWindow)(Data_DOM_Simple_Events.uiEventDOMEvent)(Data_DOM_Simple_Events.LoadEvent.value)(main$prime)(Data_DOM_Simple_Window.globalWindow);
  })();
  exports["main"] = main;;
 
})(PS["Fork"] = PS["Fork"] || {});

PS["Fork"].main();

},{}]},{},[1]);
