# The URL the site will be built for
base_url = "https://justus.science"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"

title = "Justus' Website 3.0"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
theme = "auto"
menu = [
    { name = "/bib", url = "/bib", weight = 0 },
    # Configure menu bar here
]

[[extra.socials]]
name = "github"
url = "https://github.com/JustusAdam"
icon = "github"

[[extra.socials]]
name = "bluesky"
url = "https://justusadam.bsky.social"
icon = "bluesky"

[[extra.socials]]
name = "scholar"
url = "https://scholar.google.de/citations?user=Tabbno4AAAAJ"
icon = "google-scholar"

[[extra.socials]]
name = "orcid"
url = "https://orcid.org/0000-0003-4046-534X"
icon = "orcid"

[[extra.socials]]
name = "instagram"
url = "https://instagram.com/justusadam_"
icon = "instagram"
